apiVersion: arkime.arkime.com/v1alpha1
kind: ArkimeCluster
metadata:
  name: demo
spec:
  database:
    engine: OpenSearch
    endpoints: [http://opensearch:9200]
    auth:
      unauthenticated: true
  capture:
    external:
      enabled: true
      storage:
        volumeClaim:
          size: 2Gi
      exposure:
        mode: ClusterIP
  retention:
    sessionsDays: 7
